name: recorder
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2

  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  cloud_firestore: ^4.8.4

  rename: ^2.1.1
  google_fonts: ^5.1.0
  google_sign_in: ^6.1.4
  flutter_launcher_icons: ^0.13.1

  uuid: ^3.0.7
  velocity_x: ^4.1.1
  provider: ^6.0.5
  cached_network_image: ^3.2.3
  dynamic_color: ^1.6.6
  app_usage: ^3.0.1
  installed_apps: ^1.3.1
  camera: ^0.10.5+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
